# Generated by Django 5.2.1 on 2025-06-09 18:10

from django.db import migrations
from django.utils.text import slugify


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("ledger", "Category")

    defaults = [
        "rent",
        "Leisure",
        "Electronics",
        "Utilities",
        "Clothing",
        "Health",
        "Others",
    ]

    for name in defaults:
        Category.objects.get_or_create(name=name, defaults={'slug': slugify(name)})


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
