# Generated by Django 5.2.1 on 2025-06-09 09:44

from django.db import migrations


def create_default_budget_types(apps, schema_editor):
    BudgetType = apps.get_model('ledger', 'BudgetType')

    defaults = [
        'Needs',
        'Wants',
        'Savings',
        'Investment',
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_create_default_categories'),
    ]

    operations = [
        migrations.RunPython(create_default_budget_types),
    ]
