# Generated by Django 5.2.1 on 2025-06-09 18:10

from django.db import migrations
from django.utils.text import slugify


def create_default_budget_types(apps, schema_editor):
    BudgetType = apps.get_model('ledger', 'BudgetType')

    defaults = [
        'Needs',
        'Wants',
        'Savings',
        'Investment',
    ]

    for budget_type in defaults:
        BudgetType.objects.get_or_create(budget_type=budget_type, defaults={'slug', slugify(budget_type)})


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_create_default_categories'),
    ]

    operations = [
        migrations.RunPython(create_default_budget_types),
    ]
