# Generated by Django 5.2.1 on 2025-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_create_default_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("need", "Need"),
                    ("want", "Want"),
                    ("savings", "Savings/Investment"),
                ],
                default="need",
                max_length=10,
            ),
        ),
    ]
