# Generated by Django 5.2.1 on 2025-06-09 18:10

from django.db import migrations
from django.utils.text import slugify


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("ledger", "Category")

    defaults = [
        "General",
        "Others",
    ]

    for name in defaults:
        Category.objects.get_or_create(name=name, defaults={'slug': slugify(name), "is_default": True})


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
