# Generated by Django 5.2.1 on 2025-06-13 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_create_default_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgettype",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "budget type",
                "verbose_name_plural": "budget types",
            },
        ),
        migrations.AddField(
            model_name="budgettype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budgettype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
