# Generated by Django 5.2.1 on 2025-06-16 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_budgettype_options_budgettype_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgettype',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'slug')},
        ),
    ]
