# Generated by Django 5.2.1 on 2025-06-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_alter_budgettype_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
